const contractAddress = "0x10B4fDD91924E0B160DB1272Ba84c819fc4A1512"; // Replace with your own contract address
const chain = 'ethereum'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Splendid Penguins";
const welcome_h2 = "Connect to MetaMask🦊 to Get Started";
const welcome_h3 = "Splendid Penguins";
const welcome_h4 = "Install MetaMask🦊 to Get Started ☝";  //added
const welcome_p = 'Welcome to the Splendid Penguins official minting website! Do you like Penguins? We do! We also love pixel art. That resulted in the Splendid Penguins NFT collection of 4500 unique penguins built on the Ethereum blockchain. One more splendid than other, all cute. Owning a Splendid Penguin entitles you to participate in the lottery with a prize pool of 💎20ETH. The more tokens you own, the greater your chance of winning. Connect to Metamask and mint one for yourself.';
const welcome_p2 = 'Welcome to the Splendid Penguins official minting website! Do you like Penguins? We do! We also love pixel art. That resulted in the Splendid Penguins NFT collection of 4500 unique penguins built on the Ethereum blockchain. One more splendid than other, all cute. Owning a Splendid Penguin entitles you to participate in the lottery with a prize pool of 💎20ETH. The more tokens you own, the greater your chance of winning. Install Metamask and mint one for yourself.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Splendid Penguins";
const h1_public_mint = "Splendid Penguins";
const h2_presale_coming_soon = "Splendid Penguins";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "Welcome to the Splendid Penguins official minting website! Splendid Penguins is an NFT collection of 4500 unique penguins. One more splendid than other, all cute. Mint one for yourself soon. Public minting will begin on 01 Oct 2022 21:00:00 UTC";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale!";
const p_presale_mint_already_minted = "Welcome to the Splendid Penguins official minting website! Splendid Penguins is an NFT collection of 4500 unique penguins. One more splendid than other, all cute. Mint one for yourself soon. Public minting will begin on 01 Oct 2022 21:00:00 UTC";
const p_public_mint = "Welcome to the Splendid Penguins official minting website! Splendid Penguins is an NFT collection of 4500 unique penguins. One more splendid than other, all cute. Mint yours now and participate in the lottery with a prize pool of 💎20ETH!";
const button_presale_coming_soon = "Join The Community";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Join The Community";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "MINT YOUR NFT";
const mint_failed = "Minting failed. Please try again.";
