const contractAddress = "0x9d44299a3456b0a95eB4FE06257C79f85D036346"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Splendid Penguins";
const welcome_h2 = "Connect to MetaMask🦊 to Get Started";  //added
const welcome_h3 = "Install MetaMask🦊 to Get Started";
const welcome_p = 'An NFT collection of 4500 unique penguins. One more splendid than other, all cute. Connect to Metamask and mint one for yourself.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Splendid Penguins";
const h1_public_mint = "Splendid Penguins";
const h2_presale_coming_soon = "Splendid Penguins";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "Splendid Penguins is an NFT collection of 4500 unique penguins. One more splendid than other, all cute. Mint one for yourself soon.";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale!";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you!";
const p_public_mint = "Splendid Penguins is an NFT collection of 4500 unique penguins. One more splendid than other, all cute. Mint yours now!";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Join The Community";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "MINT YOUR NFT";
const mint_failed = "Minting failed. Please try again.";
